image:
  file: .gitpod.dockerfile

tasks:
- command: |
    nvm install 12.20.2
    nvm alias default 12.20.2
    npx @angular/cli analytics off
    npm i -g @angular/cli
    npm install

vscode:
  extensions:
    - loiane.angular-extension-pack@0.9.0:6QpFyhxFQG4yh4pCiu7z2w==