image:
  file: .gitpod.dockerfile

tasks:
- command: |
    nvm install 12.20.2
    nvm set default 12.20.2
    npx @angular/cli analytics off
    npm i -g @angular/cli
    cd manish-blog
    npm install

